# see rules / samples
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# MD013:
#   # Number of characters
#   line_length: 120
#   # Number of characters for headings
#   heading_line_length: 120
#   # Number of characters for code blocks
#   code_block_line_length: 200
#   # Include code blocks
#   code_blocks: true
#   # Include tables
#   tables: false
#   # Include headings
#   headings: true
#   # Include headings
#   headers: true
#   # Strict length checking
#   strict: false
#   # Stern length checking
#   stern: false

MD033: false
MD013: false
MD041: false
MD010: false
